spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Database0529
    url: jdbc:mysql://db.homans.world:8809/music?characterEncoding=utf-8
    username: temp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080