spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db.xunyue.homans.world:8809/music?characterEncoding=utf-8&useSSL=true
    username: ENC(MzkH/HV/hNFhGThPq+WcZrnCs1AKEGfE1+YZqcwUnsyLcOlZ/ZrtnSMLoErDRU4X)
    password: ENC(IDKqQd7UsKDOHwLvIYwUH40Pol3RP1zS3vf45a49QcoqetbSVSUOOy3wQsiqhjoT)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: world.homans.xunyue.model

mapper:
  mappers: world.homans.xunyue.util.MyMapper
  not-empty: true
  identity: MYSQL

server:
  port: 9900
  http-port: 9980
  ssl:
    key-store: classpath:MyDSKeyStore.jks
    key-store-password: ENC(XZwjnWZzePGJzRRc0x8m5foWNXMVJ3TyZRedGLOnVN9f2BJb3+wcFqGpayeM3bjK)
    key-password: ENC(XZwjnWZzePGJzRRc0x8m5foWNXMVJ3TyZRedGLOnVN9f2BJb3+wcFqGpayeM3bjK)
