spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Database0529
    url: jdbc:mysql://db.homans.world:8809/music?characterEncoding=utf-8
    username: temp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  elasticsearch:
    rest:
      uris: api.homans.world:9200
      username: temp
      password: Database0529

mybatis:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: world.homans.xunyue.model

mapper:
  mappers: world.homans.xunyue.util.MyMapper
  not-empty: true
  identity: MYSQL
